name: build
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: SetLocale to zh_TW.UTF-8
        run: |
          export LANG="zh_TW.UTF-8"
          locale -a
          locale
          locale -c -k LC_NUMERIC
      - name: Install dependencies
        run: |
          brew install weasyprint
          brew install pandoc
          brew tap homebrew/cask
          brew install --cask basictex
          eval "$(/usr/libexec/path_helper)"
          sudo tlmgr update --self
          ln -s -v /Library/TeX/texbin/pdflatex /usr/local/bin/pdflatex
      - name: Install Python packages
        run: |
          pip install pillow cairosvg
          pip install mkdocs
          pip install mkdocs-material
          # pip install mkdocs-with-pdf
          pip install git+https://github.com/pandocker/pandoc-docx-pagebreak-py
      - name: Build book
        run: |
          rm -rf site
          mkdocs build --clean --verbose
      - name: Build book
        run: export LANG="zh_TW.UTF-8"; sh gendoc.sh
      - name: Deploy
        run: mkdocs gh-deploy --force --dirty --verbose
