name: build
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: SetLocale
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen zh_TW.UTF-8
          sudo localectl set-locale LANG="zh_TW.UTF-8"
          export LANG="zh_TW.UTF-8"
          sudo update-locale
          locale -a
          locale
          locale -c -k LC_NUMERIC
          localectl status
      - name: Install Dependencies
        run: |
          sudo apt-get install -y fonts-arphic-ukai fonts-arphic-uming fonts-moe-standard-song fonts-moe-standard-kai
          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji fonts-noto-cjk-extra
          sudo apt-get install -y weasyprint pandoc curl
          sudo fc-cache -f -v
      - name: Install Python Packages
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install pillow==9.0.0 cairosvg
          pip install mkdocs-with-pdf
          # pip install git+https://github.com/pandocker/pandoc-docx-pagebreak-py
      - name: Build Book
        run: |
          sh gendoc.sh
          mkdocs gh-deploy --force --clean --verbose
          sh indexnow.sh
