name: build
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: SetLocale
        run: |
                sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen zh_TW.UTF-8
                sudo localectl set-locale LANG="zh_TW.UTF-8"
                export LANG="zh_TW.UTF-8"
                sudo update-locale
                locale -a
                locale
                locale -c -k LC_NUMERIC
                localectl status
      - run: sudo apt-get install fonts-arphic-ukai fonts-arphic-uming fonts-moe-standard-song fonts-moe-standard-kai
      - run: sudo apt-get install fonts-noto fonts-noto-cjk fonts-noto-color-emoji fonts-noto-cjk-extra
      - run: sudo fc-cache -f -v
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-with-pdf
      - run: mkdocs gh-deploy --force --clean --verbose
